name: tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: run linting
        shell:
          conda install \
            --yes \
            -c conda-forge \
              black \
              shellcheck
          make lint
