name: tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: run linting
        run: |
          export PATH="/usr/share/miniconda/bin:${PATH}"
          conda install \
            --yes \
            -c conda-forge \
              black \
              shellcheck
          make lint
  smoke-tests:
    name: smoke-tests
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: run linting
        run: |
          export PATH="/usr/share/miniconda/bin:${PATH}"
          apt-get update
          apt-get install -y --no-install-recommends \
            jq
          conda install \
            --yes \
            -c conda-forge \
              numpy \
              pandas
          make smoke-tests
